package com.example.aprilLabs.apartmentListing;

import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.math.BigDecimal;
import java.util.List;

@Configuration
public class ListingConfig {

    @Bean
    CommandLineRunner commandLineRunner(
            ListingRepository listingRepository){
        return args -> {
             Listing ny1= new Listing(
                     //1, id-> generated by the database
                     "101 Manor Ave,NY",
                     3,
                     3,
                    new BigDecimal(7000)
             );

            Listing ny2= new Listing(
                   // 2, id-> generated by the database
                    "225 Harrison Ave,NY",
                    2,
                    2,
                    new BigDecimal(2600)
            );

            listingRepository.saveAll(
                    List.of(ny1, ny2)
            );

        };
    }

}
